[project]
name = "qhnodes"
description = "A custom node collection developed for ComfyUI, offering preset dimensions for Latent, loading LoRA from folders, and integrating multiple commonly used custom nodes."
version = "3.0.0"
license = {file = "LICENSE"}
dependencies = ["google-generativeai>=0.3.0", "Pillow>=10.0.0"]

[project.urls]
Repository = "https://github.com/liuqianhonga/ComfyUI-QHNodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "liuqianhong"
DisplayName = "ComfyUI-QHNodes"
Icon = "ğŸŸ"
